name: al-defects
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=26.1.2
  - numpy=2.4.6
  - scipy=1.17.1
  - ase=3.29.0
  - pandas=3.0.5
  - matplotlib=3.11.1
  - openpyxl=3.1.5
  - jupyterlab=4.6.2
  - pytest=9.1.1
  - pylibxc=7.0.0
  - qe=7.5
  - pip:
      - dftpy==2.1.2
