from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from ase.build import bulk
from ase.io import write

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.aluminum_defaults import AL_FCC_A0_TFVW_ANG


DEFAULT_A0_POINTS = "4.0000,4.0100,4.0200,4.0300,4.0400,4.0500,4.0600,4.0700,4.0800"


def _parse_float_list(text: str) -> list[float]:
    values: list[float] = []
    for chunk in str(text).split(","):
        token = chunk.strip()
        if token:
            values.append(float(token))
    if not values:
        raise ValueError("No valid floating-point values were provided.")
    return values


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Prepare a DFTpy bulk EOS raw-input archive that mirrors the QE per-point layout.")
    ap.add_argument("--outdir", default=str(ROOT / "results" / "dftpy_bulk_eos_raw_20260506"))
    ap.add_argument("--a0-points", default=DEFAULT_A0_POINTS)
    ap.add_argument("--a0-ref", type=float, default=AL_FCC_A0_TFVW_ANG)
    ap.add_argument("--pp", default=str(ROOT / "al.gga.recpot"))
    ap.add_argument("--kedf", default="TFVW")
    ap.add_argument("--ecut", type=float, default=1000.0)
    ap.add_argument("--repeat", nargs=3, type=int, default=[1, 1, 1])
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    outdir = Path(args.outdir).expanduser().resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    pp_path = Path(args.pp).expanduser().resolve()
    if not pp_path.exists():
        raise FileNotFoundError(f"Pseudopotential not found: {pp_path}")

    a0_points = _parse_float_list(args.a0_points)
    psp_dir = outdir / "pp"
    psp_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(pp_path, psp_dir / pp_path.name)

    readme = f"""# DFTpy bulk EOS raw-input archive

This folder is a per-point raw-input archive for the TFvW bulk EOS scan.

Important:

- this archive now restores the missing **input-side provenance**
- the corresponding per-point DFTpy **outputs** still need to be generated by rerunning the scan
- each point folder stores the exact structure, point manifest, and a ready run command

Suggested execution model:

- run one point per folder
- save the DFTpy text output as `dftpy.out`
- save extracted energy/stress summary as `result.json`
"""
    _write_text(outdir / "README.md", readme)

    top_manifest = {
        "workflow": "dftpy_bulk_eos_raw_archive",
        "a0_ref_A": float(args.a0_ref),
        "a0_points_A": [float(v) for v in a0_points],
        "kedf": str(args.kedf),
        "ecut_eV": float(args.ecut),
        "repeat": [int(v) for v in args.repeat],
        "pp_file": pp_path.name,
        "status": "inputs_prepared_outputs_missing_until_rerun",
    }
    _write_text(outdir / "manifest.json", json.dumps(top_manifest, indent=2))

    for a0_ang in a0_points:
        point_dir = outdir / "a0_scan" / f"a0_{a0_ang:.4f}"
        point_dir.mkdir(parents=True, exist_ok=True)
        atoms = bulk("Al", "fcc", a=float(a0_ang), cubic=True).repeat(tuple(int(v) for v in args.repeat))
        write(str(point_dir / "bulk_structure.xyz"), atoms)
        write(str(point_dir / "bulk_structure.vasp"), atoms, direct=True, vasp5=True)

        point_manifest = {
            "a0_ang": float(a0_ang),
            "natoms": int(len(atoms)),
            "repeat": [int(v) for v in args.repeat],
            "kedf": str(args.kedf),
            "ecut_eV": float(args.ecut),
            "pp_file": pp_path.name,
            "expected_outputs": ["dftpy.out", "result.json"],
        }
        _write_text(point_dir / "point_manifest.json", json.dumps(point_manifest, indent=2))

        run_text = f"""python scripts/bulk_validate.py ^
  --pp {pp_path.name} ^
  --kedf {args.kedf} ^
  --ecut {float(args.ecut):.1f} ^
  --a0 {float(a0_ang):.4f} ^
  --repeat {int(args.repeat[0])} {int(args.repeat[1])} {int(args.repeat[2])} ^
  --strains 0.0 ^
  --outdir .

Expected manual post-run files to keep:

- dftpy.out
- result.json
- bulk_structure.xyz / .vasp
"""
        _write_text(point_dir / "RUN_COMMAND.txt", run_text)

    print(f"[dftpy-bulk-archive] Prepared raw-input archive under: {outdir}")


if __name__ == "__main__":
    main()
